version: "3.8"

services:
  server:
    image: openjdk:11
    working_dir: /opt/smarttrie
    volumes:
      - ./dist/SmartTrie.jar/:/opt/smarttrie/dist/SmartTrie.jar
      - ./config/system.config:/opt/smarttrie/config/system.config
      - ./config/hosts.config:/opt/smarttrie/config/hosts.config
      - ./logs/server/:/opt/smarttrie/logs/
      - ./files/:/opt/smarttrie/files/
    command: |
      /bin/bash -c "java -Xlog:gc=debug:file=/opt/smarttrie/logs/gc.log:time -XX:+UseParallelGC -XX:+UseCompressedOops -Xms6G -Xmx6G -server -cp dist/SmartTrie.jar smarttrie.app.server.Server 0 trie-map"
    ports:
      - "11000:11000"
      - "11001:11001"

  load:
    image: openjdk:11
    working_dir: /opt/smarttrie
    depends_on:
      - server
    volumes:
      - ./dist/SmartTrie.jar/:/opt/smarttrie/dist/SmartTrie.jar
      - ./config/system.config:/opt/smarttrie/config/system.config
      - ./config/hosts.config:/opt/smarttrie/config/hosts.config
      - ./config/workload:/opt/smarttrie/config/workload
      - ./logs/client/:/opt/smarttrie/logs/
    command: |
      /bin/bash -c "java -Xmx2G -Xmx2G -server -cp dist/SmartTrie.jar site.ycsb.Client -load -s -db smarttrie.app.client.Client -P config/workload 2>&1 | tee logs/load.log"

  benchmark:
    image: openjdk:11
    working_dir: /opt/smarttrie
    depends_on:
      - server
    volumes:
      - ./dist/SmartTrie.jar/:/opt/smarttrie/dist/SmartTrie.jar
      - ./config/system.config:/opt/smarttrie/config/system.config
      - ./config/hosts.config:/opt/smarttrie/config/hosts.config
      - ./config/workload:/opt/smarttrie/config/workload
      - ./logs/client/:/opt/smarttrie/logs/
    command: |
      /bin/bash -c "java -Xmx2G -Xmx2G -server -cp dist/SmartTrie.jar site.ycsb.Client -t -s -db smarttrie.app.client.Client -threads 128 -P config/workload 2>&1 | tee logs/benchmark.log"
