---
title: "Collaborative recovery - Benchmarks"
header-includes:
  - \usepackage[brazil]{babel}
output:
  html_notebook:
    code_folding: none
    toc: yes
  pdf_document: 
    fig_crop: no
    fig_height: 4
    fig_width: 7
    toc: yes
---

```{r predef, warning=FALSE, include=FALSE}
library(stringr)
library(dplyr)
library(ggplot2)
library(scales)
library(knitr)
library(ggpubr)
library(gridExtra)
library(cowplot)

theme_set(theme_minimal())

load_ycsb_throughput = function(log_file_path) {
  ycsb_lines = regex(
    paste(
      "(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}:\\d{3}).*",
      "\\[UPDATE:",
      "Count=(.*),",
      "Max=(.*),",
      "Min=(.*),",
      "Avg=(.*),",
      "90=(.*),",
      "99=(.*),",
      "99.9=(.*),",
      "99.99=(.*)]"
    )
  )

  ycsb = str_match(readLines(log_file_path), ycsb_lines)
  ycsb = ycsb[!is.na(ycsb[, 1]),]
  ycsb = ycsb[,-1]
  colnames(ycsb) = c("ts",
                     "throughput",
                     "max",
                     "min",
                     "avg",
                     "p90",
                     "p99",
                     "p999",
                     "p9999")

  ycsb =
    as_tibble(ycsb) %>%
    mutate(ts = sub("(\\d{2}):(\\d{3})", "\\1.\\2", ts)) %>%
    mutate_at(vars(ts), as.POSIXct) %>%
    mutate_at(vars(throughput, max, min, avg, p90, p99, p999, p9999),
              as.numeric)
}

load_recovery_marks = function(server_log_path, index, start_ts, end_ts, protocol = 0) {
  if (protocol == 0) {
    recovery_start = "I just sent a request to the other replicas for the state up to CID"
    recovery_end = "I updated the state!"
  } else {
    recovery_start = "Requested state for CID"
    recovery_end = "End recovery!"
  }
  
  recovery_lines = regex(paste0(
      "(\\d{4}-\\d{2}-\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\.\\d{3}).*",
      "(",
      recovery_start,
      "|",
      recovery_end,
      ")"
    )
  )
  
  recoveries = str_match(readLines(server_log_path), recovery_lines)
  recoveries = recoveries[!is.na(recoveries[,1]),-1]
  colnames(recoveries) = c("ts", "event")
  
  if (index == -1) {
    start_txt = paste("Início recuperação")
    end_txt = paste("Fim recuperação")
  } else {
    start_txt = paste("Início recuperação", index, sep = " ")
    end_txt = paste("Fim recuperação", index, sep = " ")
  }
  

  as_tibble(recoveries) %>%
    mutate(event = sub(recovery_start, start_txt, event)) %>%
    mutate(event = sub(recovery_end, end_txt, event)) %>%
    mutate_at(vars(ts), as.POSIXct) %>%
    mutate_at(vars(event), as.factor) %>%
    filter(ts >= start_ts & ts <= end_ts)
}


load_gc_marks = function(gc_log_path, start_ts, end_ts) {
  gc_lines = regex("\\[(.*)\\+\\d+\\] GC\\(\\d+\\) (.*) \\d+\\w.*->\\d+\\w.*")
  
  pauses = str_match(readLines(gc_log_path), gc_lines)
  pauses = pauses[!is.na(pauses[, 1]), -1]
  colnames(pauses) = c("ts", "type")
  
  as_tibble(pauses) %>%
    mutate(ts = str_replace(ts, "T", " "),
           type = paste("GC", type)) %>%
    mutate_at(vars(ts), as.POSIXct) %>%
    mutate_at(vars(type), as.factor) %>%
    filter(ts >= start_ts & ts <= end_ts)
}

plot_throughput_vs_checkpoints = function(title,
                                         ycsb_log,
                                         experiment_path = NA,
                                         gc_log = NA,
                                         version = 1) {
  ycsb = load_ycsb_throughput(ycsb_log)
  start = first(ycsb$ts)
  end = last(ycsb$ts)
  
  plot = ggplot() +
    geom_line(data = ycsb, aes(ts, throughput))
  
  if (!is.na(experiment_path)) {
    
    for (server in list.files(path=experiment_path, pattern="server_\\d")) {
      recoveries = load_recovery_marks(file.path(experiment_path, server, "tmp", "SmartTrie", "logs", "app.log"), substr(server, 8,8), start, end, version)
      plot = plot + geom_vline(data = recoveries, aes(xintercept = ts, color = event), linetype = "dashed")
    }
  }
  
  if (!is.na(gc_log)) {
    gc_pauses = load_gc_marks(gc_log, start, end)
    plot = plot +
      geom_vline(data = gc_pauses,
                 aes(xintercept = ts, color = type),
                 linetype = "dotted")
  }
  
  plot +
    labs(title = title,
         x = "Time",
         y = "Throughput (rps)") +
    scale_color_discrete(name = "Markers:") +
    scale_y_continuous(breaks = pretty_breaks(15)) +
    theme(legend.position = "bottom")
}

se    = function (x) sd(x) / sqrt(length(x))
pdiff = function (a, b)  ((b - a) / a) * 100
prow   = function (a, b) c(a, b, pdiff(a, b))

generate_all_graphs = function(...) {
  for (test_dir in list.files(path="../results/")) {
    if (file.exists(file.path("..", "results", test_dir, "client", "tmp", "SmartTrie", "logs", "benchmark.log"))) {
      client_file <- "benchmark.log"
    } else {
      client_file <- "warmup.log"
    }
    
    if (dir.exists(file.path("..", "results", test_dir, "server_0"))) {
      server_folder <- "server_0"
    } else {
      server_folder <- "server_1"
    }
    
    client_path = file.path("..", "results", test_dir, "client", "tmp", "SmartTrie", "logs", client_file)
    server_path = file.path("..", "results", test_dir, server_folder, "tmp", "SmartTrie", "logs", "app.log")
    experiment_path = file.path("..", "results", test_dir)
    
    plot1 <- plot_throughput_vs_checkpoints(paste("Single", test_dir, sep = " "), client_path, experiment_path, version=0)
    plot2 <- plot_throughput_vs_checkpoints(paste("Collab", test_dir, sep = " "), client_path, experiment_path, version=1)
    grid.arrange(plot1, plot2)
  }
}

generate_range_graph = function(title, path, version, from, to, markers = TRUE) {
  client_log = paste0(path, "/client/tmp/SmartTrie/logs/benchmark.log")
  server_log = paste0(path, "/server_2/tmp/SmartTrie/logs/app.log")
  start = as.POSIXct(from)
  end = as.POSIXct(to)
  
  ycsb = load_ycsb_throughput(client_log) %>%
    filter(ts >= start & ts <= end)

  recovery = load_recovery_marks(server_log, -1, start, end, version)
  
  if (markers) {
    legend_pos = "bottom"
  } else {
    legend_pos = "none"
  }
  
  ggplot() +
    geom_line(data = ycsb, aes(ts, throughput)) +
    geom_vline(data = recovery, aes(xintercept = ts, color = event), linetype = "dashed") +
    labs(title = title,
         x = "Tempo",
         y = "Vazão (rps)") +
    scale_color_discrete(name = "Marcadores:") +
    scale_y_continuous(breaks = pretty_breaks(15)) +
    scale_x_continuous(breaks = pretty_breaks(15)) +
    theme(legend.position = legend_pos, axis.text.x = element_blank())
}

plot_blocking_vs_non_blocking = function (single_path, single_start, single_end, colab_path, colab_start, colab_end) {
  single = load_ycsb_throughput(file.path(single_path, "client", "tmp", "SmartTrie", "logs", "benchmark.log")) %>%
    filter(ts >= single_start & ts <= single_end)
  colab = load_ycsb_throughput(file.path(colab_path, "client", "tmp", "SmartTrie", "logs", "benchmark.log")) %>%
    filter(ts >= colab_start & ts <= colab_end)
  
  tibble(
    Model = c("Tradicional", "Colaborativo", "-"),
    Mean  = prow(mean(single$throughput), mean(colab$throughput)),
    SD    = prow(sd(single$throughput), sd(colab$throughput)),
    SE    = prow(se(single$throughput), se(colab$throughput))
  ) %>% mutate(across(where(is.double), round, 2))
}


```
```{r}
generate_all_graphs()
```
```{r}
generate_range_graph("Recuperação tradicional", "../results/20220612T235905", 0, "2022-06-13 05:10:51", "2022-06-13 05:11:40")
```
```{r}
generate_range_graph("Recuperação colaborativa", "../results/20220613T142738", 1, "2022-06-13 19:39:03", "2022-06-13 19:39:52")
```
```{r}
plot1 <- generate_range_graph("Recuperação tradicional", "../results/20220612T235905", 0, "2022-06-13 05:10:51", "2022-06-13 05:11:40", markers = FALSE)
plot2 <- generate_range_graph("Recuperação colaborativa", "../results/20220613T142738", 1, "2022-06-13 19:39:03", "2022-06-13 19:39:52")

plot_grid(plot1, plot2, align = "v", nrow = 2, rel_heights = c(1/2.7, 1/2))
```

```{r}
single_path = "../results/20220612T235905"
single_start = as.POSIXct("2022-06-13 05:10:51")
single_end = as.POSIXct("2022-06-13 05:11:40")
colab_path = "../results/20220613T142738"
colab_start = as.POSIXct("2022-06-13 19:39:03")
colab_end = as.POSIXct("2022-06-13 19:39:52")

kable(plot_blocking_vs_non_blocking(single_path, single_start, single_end, colab_path, colab_start, colab_end))
```

```{r}
plot1 <- generate_range_graph("Recuperação tradicional", "../results/20220613T005822", 0, "2022-06-13 06:13:12", "2022-06-13 06:14:01", markers = FALSE)
plot2 <- generate_range_graph("Recuperação colaborativa", "../results/20220613T150532", 1, "2022-06-13 20:16:29", "2022-06-13 20:17:19")

plot_grid(plot1, plot2, align = "v", nrow = 2, rel_heights = c(1/2.7, 1/2))
```
```{r}
single_path = "../results/20220613T005822"
single_start = as.POSIXct("2022-06-13 06:13:12")
single_end = as.POSIXct("2022-06-13 06:14:01")
colab_path = "../results/20220613T150532"
colab_start = as.POSIXct("2022-06-13 20:16:29")
colab_end = as.POSIXct("2022-06-13 20:17:19")

kable(plot_blocking_vs_non_blocking(single_path, single_start, single_end, colab_path, colab_start, colab_end))
```
```{r}

single_starts = as.POSIXct(c("2022-06-13 05:11:07.558", "2022-06-13 05:40:59.372", "2022-06-13 06:13:25.694", "2022-06-13 06:29:25.999", "2022-06-13 14:36:43.637"))
single_ends = as.POSIXct(c("2022-06-13 05:11:18.197", "2022-06-13 05:41:13.693", "2022-06-13 06:13:43.048", "2022-06-13 06:29:36.763", "2022-06-13 14:37:04.151"))

colab_starts = as.POSIXct(c("2022-06-13 19:39:19.387", "2022-06-13 20:02:20.629", "2022-06-13 20:16:43.092", "2022-06-13 20:34:47.931", "2022-06-13 20:52:40.577"))
colab_ends = as.POSIXct(c("2022-06-13 19:39:28.384", "2022-06-13 20:02:32.271", "2022-06-13 20:16:52.015", "2022-06-13 20:35:06.365", "2022-06-13 20:52:56.599"))

single <- data.frame(A = single_starts, B = single_ends)
single$C <- as.numeric(single$B - single$A)
single_mean <- mean(single$C)
single_sd <- sd(single$C)
single_se <- se(single$C)

colab <- data.frame(A = colab_starts, B = colab_ends)
colab$C <- as.numeric(colab$B - colab$A)
colab_mean <- mean(colab$C)
colab_sd <- sd(colab$C)
colab_se <- se(colab$C)

kable(tibble(
    Model = c("Tradicional", "Colaborativo", "-"),
    Mean  = prow(single_mean, colab_mean),
    SD    = prow(single_sd, colab_sd),
    SE    = prow(single_se, colab_se)
   ) %>% mutate(across(where(is.double), round, 2)))

```